import React, { useState } from 'react';
import { WhitelistItem } from '../types';
import { Search, Sliders, DollarSign, Download, Plus, Check, RefreshCw, Sparkles, FileDown } from 'lucide-react';
import { DEFAULT_WHITELIST } from '../data/defaultWhitelist';

interface AdminPriceManagerProps {
  whitelist: WhitelistItem[];
  setWhitelist: React.Dispatch<React.SetStateAction<WhitelistItem[]>>;
}

export const AdminPriceManager: React.FC<AdminPriceManagerProps> = ({ whitelist, setWhitelist }) => {
  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [editingMaterial, setEditingMaterial] = useState<string | null>(null);
  const [tempPrice, setTempPrice] = useState<string>('');
  const [notification, setNotification] = useState<string | null>(null);

  const categories = ['all', 'combat', 'minerals', 'redstone', 'rare', 'utility', 'building', 'food'];

  const filteredItems = whitelist.filter(item => {
    const matchesSearch = item.name.toLowerCase().includes(search.toLowerCase()) ||
                          item.material.toLowerCase().includes(search.toLowerCase());
    const matchesCategory = selectedCategory === 'all' || item.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const showNotification = (msg: string) => {
    setNotification(msg);
    setTimeout(() => setNotification(null), 3000);
  };

  const handleStartEdit = (item: WhitelistItem) => {
    setEditingMaterial(item.material);
    setTempPrice(item.price.toString());
  };

  const handleSavePrice = (material: string) => {
    const num = parseFloat(tempPrice);
    if (isNaN(num) || num < 0) {
      alert('Price must be a positive number');
      return;
    }
    setWhitelist(prev => prev.map(item => item.material === material ? { ...item, price: num } : item));
    setEditingMaterial(null);
    showNotification(`Updated price for ${material} to $${num.toLocaleString()}`);
  };

  const handleResetDefaults = () => {
    if (window.confirm('Reset all 96 item prices to the exact original Skript defaults?')) {
      setWhitelist([...DEFAULT_WHITELIST]);
      showNotification('Reset all 96 item prices to original Skript values.');
    }
  };

  // Generate downloadable prices.yml
  const handleExportYaml = () => {
    let yaml = `# ==============================================================================\n#                       Admin Whitelist & Fixed Prices\n#  Auto-generated by ArcEdgeShopSystem Admin Studio\n# ==============================================================================\n\nitems:\n`;
    for (const item of whitelist) {
      yaml += `  ${item.material}: ${item.price}\n`;
    }

    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'prices.yml';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showNotification('Exported prices.yml successfully!');
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 to-[#121620] border border-slate-800 shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2">
              <span className="px-2.5 py-0.5 rounded text-xs font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30 font-mono">
                ADMIN FIXED PRICES
              </span>
              <span className="text-xs text-slate-400">
                {whitelist.length} Whitelisted Materials Active
              </span>
            </div>
            <h2 className="text-xl font-bold text-white mt-2 font-['JetBrains_Mono',monospace]">
              Fixed Price Whitelist Manager
            </h2>
            <p className="text-xs text-slate-400 mt-1 max-w-2xl">
              All prices here are enforced by the server. Players cannot set arbitrary prices; their shop slots only offer items according to these admin-configured rates.
            </p>
          </div>

          <div className="flex items-center space-x-2">
            <button
              id="reset-prices-btn"
              onClick={handleResetDefaults}
              className="px-3 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 flex items-center space-x-1.5 transition-all"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Reset Defaults</span>
            </button>
            <button
              id="export-prices-yaml-btn"
              onClick={handleExportYaml}
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-amber-500 hover:bg-amber-400 text-slate-950 flex items-center space-x-1.5 shadow-lg shadow-amber-500/20 transition-all font-bold"
            >
              <FileDown className="w-4 h-4" />
              <span>Export prices.yml</span>
            </button>
          </div>
        </div>
      </div>

      {notification && (
        <div className="p-3 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-300 text-xs font-medium flex items-center space-x-2">
          <Check className="w-4 h-4 text-emerald-400" />
          <span>{notification}</span>
        </div>
      )}

      {/* Filter and Search Bar */}
      <div className="p-4 rounded-2xl bg-slate-900/90 border border-slate-800 shadow-md flex flex-col md:flex-row gap-3 items-center justify-between">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 absolute left-3 top-3 text-slate-500" />
          <input
            id="admin-price-search"
            type="text"
            placeholder="Search material or name..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-slate-950 border border-slate-700 rounded-xl pl-9 pr-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500"
          />
        </div>

        <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
          {categories.map((cat) => (
            <button
              key={cat}
              id={`cat-filter-${cat}`}
              onClick={() => setSelectedCategory(cat)}
              className={`px-2.5 py-1.5 rounded-lg text-xs capitalize font-semibold transition-all ${
                selectedCategory === cat
                  ? 'bg-amber-500 text-slate-950 shadow-sm'
                  : 'bg-slate-800 text-slate-400 hover:text-white'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Whitelist Items Table */}
      <div className="rounded-2xl bg-[#0e121a] border border-slate-800 overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-900/80 border-b border-slate-800 text-slate-400 font-mono">
              <tr>
                <th className="p-3.5 pl-5">Item</th>
                <th className="p-3.5">Bukkit Material</th>
                <th className="p-3.5">Category</th>
                <th className="p-3.5">Fixed Price</th>
                <th className="p-3.5 pr-5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredItems.map((item) => (
                <tr key={item.material} className="hover:bg-slate-800/40 transition-colors">
                  <td className="p-3.5 pl-5 flex items-center space-x-3">
                    <span className="text-xl">{item.iconEmoji || '📦'}</span>
                    <span className="font-bold text-white text-xs">{item.name}</span>
                  </td>
                  <td className="p-3.5 font-mono text-slate-400">{item.material}</td>
                  <td className="p-3.5">
                    <span className="px-2 py-0.5 rounded-md text-[10px] font-bold uppercase bg-slate-800 text-cyan-400 border border-slate-700">
                      {item.category}
                    </span>
                  </td>
                  <td className="p-3.5">
                    {editingMaterial === item.material ? (
                      <div className="flex items-center space-x-1.5">
                        <span className="text-amber-400 font-bold">$</span>
                        <input
                          id={`edit-price-input-${item.material.toLowerCase()}`}
                          type="number"
                          value={tempPrice}
                          onChange={(e) => setTempPrice(e.target.value)}
                          className="w-24 bg-slate-950 border border-amber-500 rounded px-2 py-1 text-xs text-white font-mono"
                          autoFocus
                        />
                      </div>
                    ) : (
                      <span className="font-mono font-bold text-amber-300 text-sm">
                        ${item.price.toLocaleString()}
                      </span>
                    )}
                  </td>
                  <td className="p-3.5 pr-5 text-right">
                    {editingMaterial === item.material ? (
                      <div className="flex items-center justify-end space-x-1.5">
                        <button
                          id={`save-price-btn-${item.material.toLowerCase()}`}
                          onClick={() => handleSavePrice(item.material)}
                          className="px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs"
                        >
                          Save
                        </button>
                        <button
                          onClick={() => setEditingMaterial(null)}
                          className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-400 text-xs"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button
                        id={`edit-price-btn-${item.material.toLowerCase()}`}
                        onClick={() => handleStartEdit(item)}
                        className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-amber-300 font-medium text-xs transition-all"
                      >
                        Edit Price
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
