import JSZip from 'jszip';
import { PLUGIN_CODEBASE } from '../data/pluginCodebase';
import { DEFAULT_WHITELIST } from '../data/defaultWhitelist';

export async function generatePluginZip(customWhitelist = DEFAULT_WHITELIST): Promise<Blob> {
  const zip = new JSZip();

  // Root files
  for (const file of PLUGIN_CODEBASE) {
    if (file.path === 'src/main/resources/prices.yml') {
      // Generate updated prices.yml with any custom prices
      let yamlContent = `# ==============================================================================\n#                       Admin Whitelist & Fixed Prices\n#  Auto-generated by ArcEdgeShopSystem Admin Studio\n# ==============================================================================\n\nitems:\n`;
      for (const item of customWhitelist) {
        yamlContent += `  ${item.material}: ${item.price}\n`;
      }
      zip.file(file.path, yamlContent);
    } else {
      zip.file(file.path, file.code);
    }
  }

  // Generate binary zip
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  return blob;
}

/**
 * Packs the plugin files, manifest, and resources into a standard JAR structure
 * (A .jar file is a zip archive with META-INF/MANIFEST.MF and resources).
 */
export async function generatePluginJar(customWhitelist = DEFAULT_WHITELIST): Promise<Blob> {
  const jar = new JSZip();

  // Standard JAR Manifest
  jar.file(
    'META-INF/MANIFEST.MF',
    `Manifest-Version: 1.0\nCreated-By: ArcEdge Build Tool (Java 21 / Paper 26.x)\nBuilt-By: ArcEdge\nImplementation-Title: ArcEdgeShopSystem\nImplementation-Version: 2.6.0\nMain-Class: com.arcedge.shopsystem.ArcEdgeShopSystem\n`
  );

  // Plugin descriptors in JAR root
  const paperPlugin = PLUGIN_CODEBASE.find(f => f.filename === 'paper-plugin.yml');
  if (paperPlugin) jar.file('paper-plugin.yml', paperPlugin.code);

  const pluginYml = PLUGIN_CODEBASE.find(f => f.filename === 'plugin.yml');
  if (pluginYml) jar.file('plugin.yml', pluginYml.code);

  const configYml = PLUGIN_CODEBASE.find(f => f.filename === 'config.yml');
  if (configYml) jar.file('config.yml', configYml.code);

  const messagesYml = PLUGIN_CODEBASE.find(f => f.filename === 'messages.yml');
  if (messagesYml) jar.file('messages.yml', messagesYml.code);

  // Generate updated prices.yml
  let yamlContent = `# ==============================================================================\n#                       Admin Whitelist & Fixed Prices\n#  Auto-generated by ArcEdgeShopSystem Admin Studio\n# ==============================================================================\n\nitems:\n`;
  for (const item of customWhitelist) {
    yamlContent += `  ${item.material}: ${item.price}\n`;
  }
  jar.file('prices.yml', yamlContent);

  // Pack all Java source files and project configs into the archive so everything is bundled
  for (const file of PLUGIN_CODEBASE) {
    jar.file(file.path, file.code);
  }

  // Generate binary JAR
  const blob = await jar.generateAsync({
    type: 'blob',
    mimeType: 'application/java-archive',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  return blob;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

